utils:
    type:     rest
    prefix:   /api/v1
    host:     projectsavoie.com
    resource: AppBundle\Controller\UtilsController

users:
    type:     rest
    prefix:   /api/v1
    host:     projectsavoie.com
    resource: AppBundle\Controller\UsersController

positionsz:
    type:     rest
    prefix:   /api/v1
    host:     projectsavoie.com
    resource: AppBundle\Controller\PositionsController